### ISSUE TITLE
segment.identify error - [ERR_ASSERTION] You must pass a message object

### ISSUE THREAD

**Issue by marcopeg** [segmentio/analytics-node#192]
Hello, I can't find a solution to this.

I am trying to identify my user with:

```
const userId = '123'
const traits = { email: 'foo@foo.it' }
segmentClient.identify(userId, traits)
```

and I get the following error:

```
{ AssertionError [ERR_ASSERTION]: You must pass a message object.
    at validateGenericEvent (/Users/marcopeg/dev/mysocial/creators/services/webapp/node_modules/@segment/loosely-validate-event/index.js:110:3)
    at looselyValidateEvent (/Users/marcopeg/dev/mysocial/creators/services/webapp/node_modules/@segment/loosely-validate-event/index.js:15:3)
    at Analytics._validate (/Users/marcopeg/dev/mysocial/creators/services/webapp/node_modules/analytics-node/index.js:58:7)
    at Analytics.identify (/Users/marcopeg/dev/mysocial/creators/services/webapp/node_modules/analytics-node/index.js:77:10)
    at Object.identify (/Users/marcopeg/dev/mysocial/creators/services/webapp/ssr/services/metrics.js:15:23)
    at _callee$ (/Users/marcopeg/dev/mysocial/creators/services/webapp/ssr/routes/graphql/login/mutations/login.js:84:17)
    at tryCatch (/Users/marcopeg/dev/mysocial/creators/services/webapp/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/marcopeg/dev/mysocial/creators/services/webapp/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/marcopeg/dev/mysocial/creators/services/webapp/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/marcopeg/dev/mysocial/creators/services/webapp/ssr/routes/graphql/login/mutations/login.js:11:191)
    at /Users/marcopeg/dev/mysocial/creators/services/webapp/ssr/routes/graphql/login/mutations/login.js:11:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

Can you point me out toward a solution?
Many thanks!

**Comment by marcopeg** [comment]
guys I'm an idiot! I was passing down userId and traits as arguments and not as object :-(

**Comment by aiswaryasiby** [comment]
Can you explain how you solved the error. I am facing the same error.

**Comment by pbassut** [comment]
@aiswaryasiby you can create your own issue showing us how you're using the library so that we can help.
But the error message is pretty clear.

**Comment by benjaminhoffman** [comment]
@pbassut the error message isn't really that clear. `You must pass a message object.` is vague because it should be `...pass an identify object`

@aiswaryasiby whereas the OP called `segmentClient.identify(userId, traits)`, they should have called `segmentClient.identify({userId, traits})`... the segment-node lib requires an object, not arguments!
