### ISSUE TITLE
Axios upgrade is not available in NPM registry

### ISSUE THREAD

**Issue by guilhermehkr** [segmentio/analytics-node#237]
Hi guys,

I'm not sure what's going on, however, the latest version of `analytics-node` doesn't come with `Axios ^0.19.0` from NPM registry.

If you try to download the library through this NPM registry [link](https://registry.npmjs.org/analytics-node/-/analytics-node-3.4.0-beta.1.tgz), you will see that the Axios version is `^0.18.1`. I double checked the NPM registry JSON [here](https://registry.npmjs.org/analytics-node/) and the Axios version specified is indeed `^0.18.1` as above.

Are you guys aware of this issue? (if this is an actual issue). Thank you for this great library

```
"3.4.0-beta.1": {
      "name": "analytics-node",
      "version": "3.4.0-beta.1",
      "description": "The hassle-free way to integrate analytics into any Node.js application",
      "license": "MIT",
      "repository": {
        "type": "git",
        "url": "git+https://github.com/segmentio/analytics-node.git"
      },
      "author": {
        "name": "Segment",
        "email": "tools+npm@segment.com",
        "url": "https://segment.com"
      },
      "engines": {
        "node": ">=4"
      },
      "size-limit": [
        {
          "limit": "25 KB",
          "path": "index.js"
        }
      ],
      "scripts": {
        "dependencies": "yarn",
        "size": "size-limit",
        "test": "standard && nyc ava && .buildscript/e2e.sh",
        "report-coverage": "nyc report --reporter=lcov > coverage.lcov && codecov",
        "np": "np --no-publish",
        "release": "yarn run np"
      },
      "keywords": [
        "analytics",
        "stats",
        "segment.io",
        "segmentio",
        "segment",
        "client",
        "driver"
      ],
      "dependencies": {
        "@segment/loosely-validate-event": "^2.0.0",
        "axios": "^0.18.1",
        "axios-retry": "^3.0.2",
        "lodash.isstring": "^4.0.1",
        "md5": "^2.2.1",
        "ms": "^2.0.0",
        "remove-trailing-slash": "^0.1.0",
        "uuid": "^3.2.1"
      },
      "devDependencies": {
        "ava": "^0.25.0",
        "basic-auth": "^2.0.1",
        "body-parser": "^1.17.1",
        "codecov": "^3.0.0",
        "commander": "^2.9.0",
        "delay": "^4.2.0",
        "express": "^4.15.2",
        "nyc": "^14.1.1",
        "pify": "^4.0.1",
        "sinon": "^7.3.2",
        "size-limit": "^1.3.5",
        "snyk": "^1.171.1",
        "standard": "^12.0.1"
      },
      "gitHead": "28a2b942d64b57a92fd0167044f73fa504ed8037",
      "bugs": {
        "url": "https://github.com/segmentio/analytics-node/issues"
      },
      "homepage": "https://github.com/segmentio/analytics-node#readme",
      "_id": "analytics-node@3.4.0-beta.1",
      "_nodeVersion": "10.16.0",
      "_npmVersion": "6.9.0",
      "dist": {
        "integrity": "sha512-+0F/y4Asc5S2qhWcYss+iCob6TTXQktwbqlIk02gcZaRxpekCbnTbJu/rcaRooVHxqp9WSzUXiWCesJYPJETZQ==",
        "shasum": "f348d60fb25f15d481ad2c2bdef53c29384b4a5e",
        "tarball": "https://registry.npmjs.org/analytics-node/-/analytics-node-3.4.0-beta.1.tgz",
        "fileCount": 5,
        "unpackedSize": 19197,
        "npm-signature": "-----BEGIN PGP SIGNATURE-----\r\nVersion: OpenPGP.js v3.0.4\r\nComment: https://openpgpjs.org\r\n\r\nwsFcBAEBCAAQBQJdC87KCRA9TVsSAnZWagAA3p4P/jGhGo/ropKnD/lw8lF2\njhzDtZ4ugoDG5pPBxE38ZZdyz0iRfoE285Xn+9b5GhpTATEcTbJsEXFUn8B2\nYk1rfWnPjGYeqWuTCgwJCjdDI7M88uOWJaAq0NCkaNXurxgYuZgC4ZwTpfO5\n7cni0bYBcyBIRTdGvAE2SbOGG3Z9UnFw7+Qd7N6ndj50VhB5ysLrmw3Gj85V\nKaUaLr6bglZVe8qPR0LfjHKmtU7OlR/rReDwJXQMYnNIImy8oNayBK4Bd/Qr\nT542Xyz4x13B6quFvpUSBGF+QMi1irkJdeU7U5I8zui9psSPoGET+2McxbgN\nDTsASshU3MuEvKNdy3ZaNubvugJ0cjyGQEVyNNfMRep5K0d3DP4vMol9wPVf\nipGc4flEmqPvKXJr5Y15gAMIoD3ZCLUpenVclLKiRqcyudgvwqSXjs4tu8hK\ntJE6uWt/pPZw+8DAfjHJ/+e91odCmX122f5B+tJWMDdrSQcjstHvK1LiP3IJ\nPxpscoy54jxq2JK/4/zgH4oqwsMnmRyK34LHcubgFF+s2WvvT3zoYt6O5Zxd\nJPg5raVX6P0mPCRwWDtSIgJ6gs95FnRigQT/yFhuELQZMP9Mn0wS6RzCQDD9\nNSnZG8j+xf9+yjYcmeYRaWNo7XIyV5+rWgGL8d9Q/geDa++KJHD+fDZVhEPo\nY0F7\r\n=/8dR\r\n-----END PGP SIGNATURE-----\r\n"
      },
      "maintainers": [
        {
          "email": "f2prateek@gmail.com",
          "name": "f2prateek"
        },
        {
          "email": "ilya@segment.io",
          "name": "ivolo"
        },
        {
          "email": "tools+npm@segment.com",
          "name": "segment-admin"
        },
        {
          "email": "tools@segment.com",
          "name": "segmentio"
        },
        {
          "email": "me@stephenmathieson.com",
          "name": "stephenmathieson"
        }
      ],
      "_npmUser": {
        "name": "segment-admin",
        "email": "tools+npm@segment.com"
      },
      "directories": {},
      "_npmOperationalInternal": {
        "host": "s3://npm-registry-packages",
        "tmp": "tmp/analytics-node_3.4.0-beta.1_1561054921395_0.2930141828018804"
      },
      "_hasShrinkwrap": false
    }```

**Comment by guilhermehkr** [comment]
It looks like you guys haven't NPM published the latest version of your library yet. 
Looking at the commit date of Axios upgrade [here](https://github.com/segmentio/analytics-node/commit/d0651cf0e2df2359ff5c473ddc152ff69d0e5d8c) which is `25 Jun 2019` I realised that you guys have published 5 days before as the NPM registry shows below

```
"time": {
    "modified": "2019-06-20T18:22:04.096Z",
    "created": "2013-01-10T08:06:45.593Z",
    "0.2.4": "2013-01-10T08:06:46.529Z",
    "0.2.5": "2013-01-10T21:23:38.909Z",
    "0.2.6": "2013-01-10T23:21:49.942Z",
    "0.2.7": "2013-01-12T04:15:51.277Z",
    "0.2.8": "2013-01-12T04:44:34.854Z",
    "0.2.9": "2013-01-17T22:00:37.368Z",
    "0.3.0": "2013-02-19T23:23:40.019Z",
    "0.4.0": "2013-04-02T04:38:12.323Z",
    "0.5.0": "2013-04-24T22:26:28.837Z",
    "0.6.0": "2014-02-20T02:46:26.897Z",
    "1.0.0": "2014-05-18T19:19:38.716Z",
    "1.0.1": "2014-07-14T20:06:53.736Z",
    "1.0.2": "2014-07-23T20:47:07.827Z",
    "1.0.3": "2014-08-06T04:52:55.282Z",
    "1.0.4": "2014-08-14T18:36:55.459Z",
    "1.1.0": "2014-08-22T19:05:40.742Z",
    "1.1.1": "2015-02-03T17:32:04.338Z",
    "1.2.0": "2015-02-18T22:32:55.941Z",
    "1.2.2": "2015-03-19T22:11:07.095Z",
    "2.0.0": "2015-09-21T18:05:46.519Z",
    "2.0.1": "2015-12-11T06:38:26.763Z",
    "2.0.2": "2016-03-03T00:10:47.760Z",
    "2.1.0": "2016-04-01T06:03:46.702Z",
    "2.1.1": "2017-01-31T19:59:34.989Z",
    "2.3.0": "2017-03-13T16:50:00.282Z",
    "2.4.0": "2017-03-13T18:17:03.287Z",
    "2.4.1": "2017-05-05T22:15:31.540Z",
    "3.0.0": "2017-07-27T17:50:30.880Z",
    "3.1.0": "2017-10-16T15:07:36.882Z",
    "3.1.1": "2017-10-18T03:10:13.349Z",
    "3.2.0": "2017-12-07T04:31:17.947Z",
    "3.2.1-0": "2018-01-18T21:27:36.325Z",
    "3.3.0-beta.1": "2018-01-18T21:32:54.504Z",
    "3.3.0-beta.2": "2018-03-03T00:09:09.897Z",
    "3.3.0": "2018-04-23T22:55:08.558Z",
    "3.4.0-beta.1": "2019-06-20T18:22:01.500Z"
  }
```

**Comment by charleycodes** [comment]
The need for the update is due to a security vulnerability: https://github.com/axios/axios/issues/2131

**Comment by broom9** [comment]
Is this project still being maintained? The last release was more than half a year ago, and this security vulnerability has been there for a long time.

**Comment by dzoba** [comment]
We are also experiencing problems because of this.  Specifically we are getting errors in our logs that we would like to clean up but can't because analytics-node is using an old version of axios.  Would love to see a new version published.

```
(node:91157) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:174:11)
    at new Buffer (buffer.js:257:3)
```
