### ISSUE TITLE
Can't use group as described in documetation

### ISSUE THREAD

**Issue by Mihailoff** [segmentio/analytics-node#96]
https://segment.com/docs/spec/group/

```
analytics.group(team.uuid, {
                name: "something",
                non_common: "something",
                non_common: "something",
                createdAt: '2016-12-20T22:39:36.338841+00:00',
                non_common: "something",
                website: "website"
              });
```

I get 

```
{ AssertionError: You must pass a message object.
    at validateGenericEvent (/usr/src/app/node_modules/@segment/loosely-validate-event/index.js:107:3)
    at looselyValidateEvent (/usr/src/app/node_modules/@segment/loosely-validate-event/index.js:12:3)
    at Analytics.group (/usr/src/app/node_modules/analytics-node/lib/index.js:66:3)
    at data.values.forEach.team (/usr/src/app/routes/index.js:129:40)
    at Array.forEach (native)
    at Request._callback (/usr/src/app/routes/index.js:127:25)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'You must pass a message object.',
  generatedMessage: false }
```

analytics-nodev2.4.1

**Comment by stevenmiller888** [comment]
Hey @Mihailoff, the example you referenced is the `group` call from our analytics.js library. With our Node.js library, you'll want to make sure to follow [this](https://segment.com/docs/sources/server/node/#group) doc. This should do the trick:

```
analytics.group({
  groupId: team.uuid,
  name: "something",
  non_common: "something",
  non_common: "something",
  createdAt: '2016-12-20T22:39:36.338841+00:00',
  non_common: "something",
  website: "website"
});
```

One more thing, please make sure to include a `userId`, as it is required.
